from typing import Protocol
from aurora.task import Task
from uuid import UUID

class StorageProtocol(Protocol):
    def create_task(self, task: Task) -> None: ...

    def get_task(self, id: UUID) -> Task: ...

    def get_all(self) -> list[Task]: ...

    def update(self, updated_task: Task) -> None: ...

    def delete(self, id: UUID) -> None: ...